### PR TITLE
Implement Product and Product List

### PR DESCRIPTION
**Pull request by Velosofy**
- Implemented Product (Model, Repository, Service)
- Implemented Product List Screen
- Add new router `/products`
- Add new button in Onboarding Screen to jump to Product List Screen

Screenshot_1694702680

### CODE REVIEW

**Comment by Velosofy** [comment]
Force-pushed 3x karna lupa fetch sma revert `.gitignore`, sorry wkwk

**Comment by reyys** [comment]
Nice !!!

**Review by reyys — COMMENTED** [review]
Menunggu commit baru untuk tombol add to cart

**Comment by Velosofy** [comment]
Added and screenshot changed

**Review by reyys — APPROVED** [review]
Produc Page ( Static ) Finished ✓

**Pull request merged**
